Adm 793 [frontend] Reduce the time of timeout to 10 minutes
au-heartbeat/Heartbeat pull request #1141
Opened 2024-03-13 02:41 UTC by doujiao-001

## Summary
Reduce the time of timeout to 10 minutes

## Before

_Description_

**Screenshots**
<img width="862" alt="image" src="https://github.com/au-heartbeat/Heartbeat/assets/141200259/6dc92b59-506c-42eb-b302-5c4ba9c1ec42">

## After

_Description_

**Screenshots**

<img width="722" alt="image" src="https://github.com/au-heartbeat/Heartbeat/assets/141200259/237db071-0f27-42c4-9329-c6d270808a2b">

## Note

_Null_

2024-03-13 03:21 UTC, guzhongren commented
Reverify? Verify again?

2024-03-13 03:33 UTC, guzhongren requested changes

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/containers/ConfigStep/ConfigButtonGroup.test.tsx
> +  const setup = (isVerified: boolean, isLoading: boolean, isHBTimeOut: boolean, isDisableVerifyButton: boolean) => {
IsHBTimeout?isConfigTimeout??

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/containers/ConfigStep/ConfigButtonGroup.test.tsx
> +    setup(true, false, false, false); // Use a different moduleType for clarity
?

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/containers/ConfigStep/ConfigButtonGroup.test.tsx
> +  it('should render a disabled VerifyButton with "Verified" text when isVerified is true and isLoading is false', () => {
When - given，看一哈should given when 分别写什么

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/containers/ConfigStep/ConfigButtonGroup.test.tsx
> +    setup(false, false, true, false); // Use a different moduleType for clarity
?

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/containers/ConfigStep/TimeoutAlet.test.tsx
> +    setup(setIsShowAlert, true, true, 'Board'); // Use a different moduleType for clarity
这么多注释干什么？

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/hooks/useVerifyBoardEffect.test.tsx
> +  it('should clear email validatedError when updateField by Email', async () => {
Should Given when

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/hooks/useVerifyBoardEffect.test.tsx
> +  it('should set timeout is true when getVerifyBoard api is timeout', async () => {
Given

2024-03-13 03:33 UTC, guzhongren commented on frontend/__tests__/hooks/useVerifySourceControlTokenEffect.test.tsx
> +      code: HEARTBEAT_EXCEPTION_CODE.TIMEOUT,
为什么常量要和项目名挂钩？

2024-03-13 03:33 UTC, guzhongren commented on frontend/src/containers/ConfigStep/SourceControl/index.tsx
> +      <TimeoutAlert
能把这个组件当child传进来吗？隔离组件深度

2024-03-13 04:06 UTC, doujiao-001 commented on frontend/__tests__/containers/ConfigStep/ConfigButtonGroup.test.tsx
> +  const setup = (isVerified: boolean, isLoading: boolean, isHBTimeOut: boolean, isDisableVerifyButton: boolean) => {
收到，我理解是尽量避免变量名不涉及项目信息？比如IsHBTimeout中HB涉及到了，应换个普通点的名称？

2024-03-13 04:09 UTC, doujiao-001 commented on frontend/__tests__/containers/ConfigStep/TimeoutAlet.test.tsx
> +    setup(setIsShowAlert, true, true, 'Board'); // Use a different moduleType for clarity
好嘞，以后注意 避免留有无用注释

2024-03-13 04:11 UTC, doujiao-001 commented on frontend/__tests__/hooks/useVerifySourceControlTokenEffect.test.tsx
> +      code: HEARTBEAT_EXCEPTION_CODE.TIMEOUT,
这个是之前存在的变量名，我再去找相关人员确认下 是否更改一下 不要包含项目名称

2024-03-14 02:18 UTC, neomgb approved these changes

2024-03-14 07:06 UTC, guzhongren approved these changes

2024-03-14 07:06 UTC, merged

2024-03-14 07:07 UTC, guzhongren commented
2new issues in sonar cloud