ADM-873:[frontend][backend] fix: fix success notification
au-heartbeat/Heartbeat pull request #1327
Opened 2024-04-03 09:27 UTC by TingyuDong

## Summary

...

## Before

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## After

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## Note

_Null_

2024-04-03 14:07 UTC, guzhongren requested changes

2024-04-03 14:07 UTC, guzhongren commented on backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
> +		void shouldUpdateDoraMetricDataAndHasCsvFileCreateSuccessfulIsFalseWhenMetricIsDoraAndNotCreateCsv()
这个测试的业务意义是什么， 测试名称不要写技术术语，看不懂

2024-04-07 02:56 UTC, TingyuDong commented on backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
> +		void shouldUpdateDoraMetricDataAndHasCsvFileCreateSuccessfulIsFalseWhenMetricIsDoraAndNotCreateCsv()
This one has been changed.

2024-04-07 14:41 UTC, guzhongren approved these changes

2024-04-09 02:32 UTC, merged