ADM-952 [frontend][backend]: change the frontend for the vietnam holiday
au-heartbeat/Heartbeat pull request #1488
Opened 2024-06-17 09:25 UTC by zhou-yinyuan

## Summary

...

## Before

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## After

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## Note

_Null_

2024-06-17 14:56 UTC, guzhongren requested changes

2024-06-17 14:56 UTC, guzhongren commented on backend/src/main/java/heartbeat/service/report/VietnamHoliday.java
> +		log.info("Start to get vietnam holiday by year: {}", year);
vietnam?

2024-06-17 14:56 UTC, guzhongren commented on backend/src/main/resources/application-e2e.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
security issue

2024-06-17 14:56 UTC, guzhongren commented on backend/src/main/resources/application-local.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
security issue

2024-06-17 14:56 UTC, guzhongren commented on backend/src/main/resources/application.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
security issue

2024-06-18 01:08 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/service/report/VietnamHoliday.java
> +		log.info("Start to get vietnam holiday by year: {}", year);
yes

2024-06-18 07:03 UTC, zhou-yinyuan commented on backend/src/main/resources/application-e2e.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
done

2024-06-18 07:03 UTC, zhou-yinyuan commented on backend/src/main/resources/application-local.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
done

2024-06-18 07:03 UTC, zhou-yinyuan commented on backend/src/main/resources/application.yml
> +  apiKey: RzQjN0CCwMrABymlmUlymWWi79Oju3Ff
done

2024-06-18 07:20 UTC, zhou-yinyuan commented
close the PR because the api key

2024-06-18 07:20 UTC, closed without merging