ADM-973 [frontend][backend]: share api
au-heartbeat/Heartbeat pull request #1509
Opened 2024-07-02 02:39 UTC by zhou-yinyuan

## Summary

...

## Before

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## After

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## Note

_Null_

2024-07-05 03:23 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			Files.createDirectories(path);
done

2024-07-05 03:23 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +		if (file.exists()) {
done

2024-07-05 03:24 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +		if (folder.exists() && folder.isDirectory()) {
done

2024-07-05 03:24 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			InputStream inputStream = new FileInputStream(file);
done

2024-07-05 03:24 UTC, zhou-yinyuan commented on backend/src/main/java/heartbeat/handler/AsyncReportRequestHandler.java
> +		if (folder.exists() && folder.isDirectory()) {
done

2024-07-05 07:54 UTC, guzhongren approved these changes

2024-07-08 09:40 UTC, guzhongren requested changes

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
> +		return reportService.getShareReportInfo(uuid);
add log to record the request finished.

same as others

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
>  		log.info("Start to generate report");
record the parameter(uuid) at the start and end of the log

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
> +		return reportService.generateReportId();
add log

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/dto/response/ShareApiDetailsResponse.java
> +	private List<String> reportUrls;
rename to `reportURLs`

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			log.info("Failed create {} directory", path);
Failed to create ....

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			log.info("Failed create {} directory", path);
Log.error

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +				log.error("Failed read file type: {}, uuid: {}, file name: {}, reason: {}", fileType.getType(), uuid,
Failed to read.....

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +						"Failed read file " + fileType.getType() + " " + uuid + " " + realFileName);
Failed to read....

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			log.info("Failed remove file type: {}, uuid: {}, file name: {}", fileType.getType(), uuid, realFileName);
Failed to remove
log.error


Please check all your error log

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +					"Failed remove " + fileType.getType() + ", uuid: " + uuid + " file with file:" + fileName);
Failed to remove

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +		log.info("Start to write file type: {}, uuid: {}, file name: {}", fileType.getType(), uuid, realFileName);
logs should be a pair, there are `start and end` for the log

2024-07-08 09:40 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			log.error("Failed write file type: {}, uuid: {}, file name: {}, reason: {}", fileType.getType(), uuid,
Failed to write....

2024-07-10 02:42 UTC, guzhongren approved these changes
@zhou-yinyuan small change 
Approval it, merge it after changing with the comments

2024-07-10 02:42 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
> +		log.info("successfully to generate report_reportId: {}", uuid);
Successfully generate

2024-07-10 02:42 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
> +		log.info("successfully to generate report_reportId: {}", uuid);
same as others..
Keep first character as Upcase

2024-07-10 02:42 UTC, guzhongren commented on backend/src/main/java/heartbeat/controller/report/ReportController.java
> +		log.info("successfully to generate uuid");
log the `uuid`

2024-07-10 02:42 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +				log.info("Successfully to read file type: {}, uuid: {}, file name: {}", fileType.getType(), uuid,
No `to`

2024-07-10 02:42 UTC, guzhongren commented on backend/src/main/java/heartbeat/repository/FileRepository.java
> +			log.info("Successfully to write file type: {}, uuid: {}, file name: {}", fileType.getType(), uuid,
same issue

2024-07-11 04:13 UTC, merged