ADM-1009 [frontend]: fix the 4xx error
au-heartbeat/Heartbeat pull request #1609
Opened 2024-09-18 06:14 UTC by zhou-yinyuan

## Summary

...

## Before

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## After

_Description_

**Screenshots**
If applicable, add screenshots to help explain behavior of your code.

## Note

_Null_

2024-09-18 09:21 UTC, davidwangcn9 requested changes

2024-09-18 09:33 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetMetricsStepsEffect.ts
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
maybe no, becase the code may be of string type. `type ResponseCodeType = number | string | undefined | null;`

2024-09-18 09:33 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx
> +        if (response.code === 400 || response.code === 401 || response.code === 403 || response.code === 404) {
same as above

2024-09-18 09:34 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationCrewEffect.tsx
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
same as above

2024-09-18 09:36 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationRepoEffect.tsx
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
same as above

2024-09-19 02:52 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetMetricsStepsEffect.ts
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
done

2024-09-19 02:52 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx
> +        if (response.code === 400 || response.code === 401 || response.code === 403 || response.code === 404) {
done

2024-09-19 02:52 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationCrewEffect.tsx
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
done

2024-09-19 02:52 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationRepoEffect.tsx
> +      if (code === 400 || code === 401 || code === 403 || code === 404) {
done

2024-09-19 03:00 UTC, davidwangcn9 requested changes

2024-09-19 03:00 UTC, davidwangcn9 commented on frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx
> +        } else if (response.code == 200) {
Why change === to ==?

2024-09-19 03:02 UTC, zhou-yinyuan commented on frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx
> +        } else if (response.code == 200) {
=== is ok

2024-09-19 03:04 UTC, davidwangcn9 approved these changes

2024-09-19 03:13 UTC, merged